name: Docker publish production image

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled
  schedule:
    - cron: '0 5 7 * *' # At 05:00 UTC on day-of-month 7.
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - id: build_info
        name: build info
        run:
          echo ::set-output name=tags::ghcr.io/${GITHUB_REPOSITORY//docker-/}:prod-${GITHUB_REF#refs/tags/}
      - name: setup qemu
        uses: docker/setup-qemu-action@v1
      - name: setup buildx
        uses: docker/setup-buildx-action@v1
      - name: login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: kronostechnologies-build
          password: ${{ secrets.GHCR_TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.build_info.outputs.tags }}
          platforms: linux/amd64,linux/arm64
          push: true
          labels: |
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.description=${{ github.event.repository.description }}
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.revision=${{ github.sha }}
