name: Docker publish production image

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled
  schedule:
    - cron: '0 5 7 * *' # At 05:00 UTC on day-of-month 7.
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: build_info
        name: build info
        shell: bash
        run: |
          set -eo pipefail

          current_image="ghcr.io/${GITHUB_REPOSITORY//docker-/}:v$(git describe --tags --abbrev=0)"
          tags="ghcr.io/${GITHUB_REPOSITORY//docker-/}:prod-$(git describe --tags --abbrev=0)"
          echo "tags=${tags}" >> $GITHUB_OUTPUT
          echo "current_image=${current_image}" >> $GITHUB_OUTPUT
      - name: setup qemu
        uses: docker/setup-qemu-action@v1
      - name: setup buildx
        uses: docker/setup-buildx-action@v1
      - name: login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: kronostechnologies-build
          password: ${{ secrets.GHCR_TOKEN }}
      - name: tag and push
        id: push_prod
        shell: bash
        run: |
          set -eo pipefail

          docker image tag ${{ steps.build_info.outputs.current_image }} ${{ steps.build_info.outputs.tags }}
          docker push ${{ steps.build_info.outputs.tags }}
